// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WareHouseApi.Data;

#nullable disable

namespace WareHouse.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240925093822_AddModelNhapKho")]
    partial class AddModelNhapKho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WareHouse.Models.Domain.NhapKho", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("kho_id")
                        .HasColumnType("int");

                    b.Property<string>("loai_nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ncc_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_nhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_giao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noi_dung_nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sl_nhap")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("kho_id");

                    b.HasIndex("ncc_id");

                    b.ToTable("nhap_kho");
                });

            modelBuilder.Entity("WareHouse.Models.Domain.NhapKhoCT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("dvt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("gia_nhap")
                        .HasColumnType("real");

                    b.Property<DateTime>("han_su_dung")
                        .HasColumnType("datetime2");

                    b.Property<string>("hang_sx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinh_anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_het_han")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_nhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nhap_kho_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nhom_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quy_cach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("san_pham_id")
                        .HasColumnType("int");

                    b.Property<int>("sl_nhap")
                        .HasColumnType("int");

                    b.Property<int>("sl_ton")
                        .HasColumnType("int");

                    b.Property<int>("sl_xuat")
                        .HasColumnType("int");

                    b.Property<string>("so_lo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thong_tin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("nhap_kho_id");

                    b.HasIndex("san_pham_id");

                    b.ToTable("nhap_kho_ct");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.Kho", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hien_thi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("kho");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.NhaCC", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hien_thi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loai_ncc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_dai_dien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nv_phu_trach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_day_du")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_ncc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinh_trang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ncc");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.NhomSanPham", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("loai_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("nhom_san_pham");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.SanPham", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("dia_chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dvt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("gia_nhap")
                        .HasColumnType("real");

                    b.Property<DateTime>("han_su_dung")
                        .HasColumnType("datetime2");

                    b.Property<string>("hang_sx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hien_thi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinh_anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nhom_san_pham_id")
                        .HasColumnType("int");

                    b.Property<string>("quy_cach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sl_nhap")
                        .HasColumnType("int");

                    b.Property<int>("sl_toi_da")
                        .HasColumnType("int");

                    b.Property<int>("sl_toi_thieu")
                        .HasColumnType("int");

                    b.Property<int>("sl_ton")
                        .HasColumnType("int");

                    b.Property<int>("sl_xuat")
                        .HasColumnType("int");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thong_tin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("nhom_san_pham_id");

                    b.ToTable("san_pham");
                });

            modelBuilder.Entity("WareHouse.Models.Domain.NhapKho", b =>
                {
                    b.HasOne("WareHouseApi.Models.Domain.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("kho_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WareHouseApi.Models.Domain.NhaCC", "Ncc")
                        .WithMany()
                        .HasForeignKey("ncc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("Ncc");
                });

            modelBuilder.Entity("WareHouse.Models.Domain.NhapKhoCT", b =>
                {
                    b.HasOne("WareHouse.Models.Domain.NhapKho", "NhapKho")
                        .WithMany()
                        .HasForeignKey("nhap_kho_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WareHouseApi.Models.Domain.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("san_pham_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.SanPham", b =>
                {
                    b.HasOne("WareHouseApi.Models.Domain.NhomSanPham", "NhomSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("nhom_san_pham_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomSanPham");
                });

            modelBuilder.Entity("WareHouseApi.Models.Domain.NhomSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
